### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/subfinder#738]
# Description

- [ ] Improve Overall Performance of `subfinder` by implementing Worker-Pool architecture
- [ ] Add `-concurrency` flag
- [ ] Remove redundant code and optimize 
- [ ] A followup ticket should be created in `nuclei` after successful implementation 

## Implementation

Worker-Pool can be implemented by implementing a channel `muxer` and `demuxer` 

```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/subfinder/issues/718
- [ ] https://github.com/projectdiscovery/subfinder/issues/737
```
