### ISSUE TITLE
Upgrade deps and maintenance

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/subfinder#761]
### TODO

- [x] Bump `ratelimit` to latest version (`go get -u github.com/projectdiscovery/ratelimit@latest`) and resolve any api change issues if any
- [x] Replace `github.com/projectdiscovery/fileutil` => `github.com/projectdiscovery/utils/file`
- [x] `go mod tidy`
- [x] Verify and then Remove `&gitlab.Source{}` from `AllSources` array 
   - gitlab seems to have disabled `blob` search in api verify it and then proceed to remove it
