### ISSUE TITLE
Add Missing Source

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/subfinder#945]
### Please describe your feature request:
Found Important Sources are missing such as mentioned below.

GitLab Subdomain Enumeration - https://github.com/gwen001/gitlab-subdomains

URLScan - #282 (urlscan.io was removed in 2020 due to multiple issue in API issues)

TLS,SSL Certificate subdomain enumeration :-
Reference: https://sidxparab.gitbook.io/subdomain-enumeration-guide/active-enumeration/tls-csp-cname
Tool : https://github.com/glebarez/cero

### Describe the use case of this feature:

```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/subfinder/issues/956
- [ ] https://github.com/projectdiscovery/subfinder/issues/955
- [ ] https://github.com/projectdiscovery/subfinder/issues/959
- [ ] Enumerate Subdomain from TLS, SSL Certificate
```

**Comment by ehsandeep** [comment]
@DhiyaneshGeek subdomains from ssl/tlsx can be fetched using tlsx - https://github.com/projectdiscovery/tlsx/releases/tag/v1.1.5
